import { Account, Budget, FinancialProfile, Friend, SplitBill, Transaction } from "@/types/finance";

export const INITIAL_PROFILE: FinancialProfile = {
  name: "Alex Morgan",
  email: "alex.morgan@finance.io",
  currencySymbol: "$",
  currencyCode: "USD",
  monthlySavingsTarget: 3000,
};

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: "acc-1",
    name: "Main Checking",
    institution: "Bank of America",
    type: "checking",
    accountNumber: "•••• 4821",
    balance: 12450.0,
    currency: "USD",
    accent: "moss",
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "acc-2",
    name: "Emergency Fund",
    institution: "Marcus by Goldman Sachs",
    type: "savings",
    accountNumber: "•••• 9102",
    balance: 24800.0,
    currency: "USD",
    accent: "moss",
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "acc-3",
    name: "Sapphire Preferred",
    institution: "Chase",
    type: "credit",
    accountNumber: "•••• 7319",
    balance: -1250.0,
    currency: "USD",
    accent: "brass",
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "acc-4",
    name: "Retirement & Index Fund",
    institution: "Vanguard",
    type: "investment",
    accountNumber: "•••• 3042",
    balance: 12250.0,
    currency: "USD",
    accent: "info",
    createdAt: "2026-01-01T00:00:00.000Z",
  },
];

export const INITIAL_BUDGETS: Budget[] = [
  {
    id: "b-1",
    category: "Housing & Rent",
    allocated: 1800,
    period: "Monthly",
    color: "bg-xenia-moss-600",
  },
  {
    id: "b-2",
    category: "Groceries & Food",
    allocated: 800,
    period: "Monthly",
    color: "bg-xenia-moss-700",
  },
  {
    id: "b-3",
    category: "Utilities & Bills",
    allocated: 350,
    period: "Monthly",
    color: "bg-xenia-brass-500",
  },
  {
    id: "b-4",
    category: "Transportation & Gas",
    allocated: 400,
    period: "Monthly",
    color: "bg-xenia-stone-700",
  },
  {
    id: "b-5",
    category: "Dining Out & Entertainment",
    allocated: 350,
    period: "Monthly",
    color: "bg-xenia-moss-500",
  },
  {
    id: "b-6",
    category: "Healthcare & Wellness",
    allocated: 200,
    period: "Monthly",
    color: "bg-xenia-brass-600",
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-1",
    date: "2026-09-12",
    description: "Monthly Salary Deposit",
    category: "Salary & Income",
    accountId: "acc-1",
    amount: 5200.0,
    type: "income",
    status: "paid",
    notes: "Primary employer monthly payroll",
    createdAt: "2026-09-12T09:00:00.000Z",
  },
  {
    id: "tx-2",
    date: "2026-09-11",
    description: "Whole Foods Market",
    category: "Groceries & Food",
    accountId: "acc-3",
    amount: 142.5,
    type: "expense",
    status: "paid",
    notes: "Weekly organic groceries",
    createdAt: "2026-09-11T14:30:00.000Z",
  },
  {
    id: "tx-3",
    date: "2026-09-10",
    description: "Apartment Rent",
    category: "Housing & Rent",
    accountId: "acc-1",
    amount: 1600.0,
    type: "expense",
    status: "paid",
    notes: "September apartment lease",
    createdAt: "2026-09-10T08:00:00.000Z",
  },
  {
    id: "tx-4",
    date: "2026-09-09",
    description: "Freelance UI/UX Consulting",
    category: "Freelance & Consulting",
    accountId: "acc-1",
    amount: 1220.0,
    type: "income",
    status: "paid",
    notes: "Design sprint client milestone",
    createdAt: "2026-09-09T16:00:00.000Z",
  },
  {
    id: "tx-5",
    date: "2026-09-08",
    description: "Electric & Clean Water Utility",
    category: "Utilities & Bills",
    accountId: "acc-3",
    amount: 85.2,
    type: "expense",
    status: "pending",
    notes: "Municipal utilities bill",
    createdAt: "2026-09-08T11:20:00.000Z",
  },
  {
    id: "tx-6",
    date: "2026-09-07",
    description: "Artisan Coffee & Bakery",
    category: "Dining Out & Entertainment",
    accountId: "acc-3",
    amount: 14.5,
    type: "expense",
    status: "paid",
    createdAt: "2026-09-07T08:45:00.000Z",
  },
  {
    id: "tx-7",
    date: "2026-09-05",
    description: "Netflix & Cloud Services",
    category: "Subscriptions & Software",
    accountId: "acc-3",
    amount: 19.99,
    type: "expense",
    status: "paid",
    createdAt: "2026-09-05T00:01:00.000Z",
  },
  {
    id: "tx-8",
    date: "2026-09-03",
    description: "Vanguard Dividend Payout",
    category: "Investments & Dividends",
    accountId: "acc-4",
    amount: 84.6,
    type: "income",
    status: "paid",
    createdAt: "2026-09-03T09:15:00.000Z",
  },
  {
    id: "tx-9",
    date: "2026-09-02",
    description: "Chevron Gas Station",
    category: "Transportation & Gas",
    accountId: "acc-3",
    amount: 54.2,
    type: "expense",
    status: "paid",
    createdAt: "2026-09-02T18:30:00.000Z",
  },
  {
    id: "tx-10",
    date: "2026-08-28",
    description: "Trader Joe's Supermarket",
    category: "Groceries & Food",
    accountId: "acc-3",
    amount: 112.4,
    type: "expense",
    status: "paid",
    createdAt: "2026-08-28T17:10:00.000Z",
  },
  {
    id: "tx-11",
    date: "2026-08-25",
    description: "Gym & Wellness Membership",
    category: "Healthcare & Wellness",
    accountId: "acc-3",
    amount: 95.0,
    type: "expense",
    status: "paid",
    createdAt: "2026-08-25T07:00:00.000Z",
  },
  {
    id: "tx-12",
    date: "2026-08-15",
    description: "Bi-Weekly Salary Deposit",
    category: "Salary & Income",
    accountId: "acc-1",
    amount: 2600.0,
    type: "income",
    status: "paid",
    createdAt: "2026-08-15T09:00:00.000Z",
  },
  {
    id: "tx-13",
    date: "2026-08-10",
    description: "Apartment Rent",
    category: "Housing & Rent",
    accountId: "acc-1",
    amount: 1600.0,
    type: "expense",
    status: "paid",
    createdAt: "2026-08-10T08:00:00.000Z",
  },
  {
    id: "tx-14",
    date: "2026-08-01",
    description: "Bi-Weekly Salary Deposit",
    category: "Salary & Income",
    accountId: "acc-1",
    amount: 2600.0,
    type: "income",
    status: "paid",
    createdAt: "2026-08-01T09:00:00.000Z",
  },
];

export const INITIAL_SPLIT_BILLS: SplitBill[] = [
  {
    id: "sb-1",
    title: "Osteria Dinner & Drinks",
    date: "2026-09-11",
    category: "Dining Out & Entertainment",
    totalAmount: 180.0,
    paidBy: "Alex Morgan",
    paidByCurrentUser: true,
    payerAccountId: "acc-3",
    splitMethod: "itemized",
    notes: "Friday dinner with team, includes appetizers and dessert",
    tax: 15.0,
    tip: 25.0,
    status: "partial",
    createdAt: "2026-09-11T20:30:00.000Z",
    items: [
      { id: "item-1", name: "Truffle Pasta & Risotto", amount: 62.0, assignedTo: ["p-1", "p-2"] },
      { id: "item-2", name: "Wood-Fired Pizza", amount: 36.0, assignedTo: ["p-2", "p-3"] },
      { id: "item-3", name: "Cocktails & Wine Pitcher", amount: 42.0, assignedTo: ["p-1", "p-2", "p-3"] },
    ],
    participants: [
      {
        id: "p-1",
        name: "Alex Morgan",
        email: "alex.morgan@finance.io",
        isCurrentUser: true,
        shareAmount: 65.0,
        status: "paid",
        settledAt: "2026-09-11T20:30:00.000Z",
      },
      {
        id: "p-2",
        name: "Sarah Jenkins",
        email: "sarah.j@techcorp.com",
        isCurrentUser: false,
        shareAmount: 68.0,
        status: "paid",
        settledAt: "2026-09-12T10:15:00.000Z",
      },
      {
        id: "p-3",
        name: "David Kim",
        email: "david.kim@designco.com",
        isCurrentUser: false,
        shareAmount: 47.0,
        status: "unpaid",
      },
    ],
  },
  {
    id: "sb-2",
    title: "Lake Tahoe Cabin Rental",
    date: "2026-09-06",
    category: "Housing & Rent",
    totalAmount: 840.0,
    paidBy: "Marcus Vance",
    paidByCurrentUser: false,
    splitMethod: "equal",
    notes: "Labor Day weekend cabin rental split equally between 4 people",
    status: "pending",
    createdAt: "2026-09-06T15:00:00.000Z",
    participants: [
      {
        id: "p-201",
        name: "Marcus Vance",
        email: "marcus.v@gmail.com",
        isCurrentUser: false,
        shareAmount: 210.0,
        status: "paid",
        settledAt: "2026-09-06T15:00:00.000Z",
      },
      {
        id: "p-202",
        name: "Alex Morgan",
        email: "alex.morgan@finance.io",
        isCurrentUser: true,
        shareAmount: 210.0,
        status: "unpaid",
      },
      {
        id: "p-203",
        name: "Elena Rostova",
        email: "elena.r@gmail.com",
        isCurrentUser: false,
        shareAmount: 210.0,
        status: "paid",
        settledAt: "2026-09-07T12:00:00.000Z",
      },
      {
        id: "p-204",
        name: "Liam O'Connor",
        email: "liam.oc@gmail.com",
        isCurrentUser: false,
        shareAmount: 210.0,
        status: "unpaid",
      },
    ],
  },
  {
    id: "sb-3",
    title: "High-Speed Fiber Internet",
    date: "2026-09-01",
    category: "Utilities & Bills",
    totalAmount: 90.0,
    paidBy: "Alex Morgan",
    paidByCurrentUser: true,
    payerAccountId: "acc-1",
    splitMethod: "equal",
    notes: "September Gigabit Fiber Internet split with roommate",
    status: "settled",
    createdAt: "2026-09-01T08:00:00.000Z",
    participants: [
      {
        id: "p-301",
        name: "Alex Morgan",
        email: "alex.morgan@finance.io",
        isCurrentUser: true,
        shareAmount: 45.0,
        status: "paid",
        settledAt: "2026-09-01T08:00:00.000Z",
      },
      {
        id: "p-302",
        name: "Jordan Lee",
        email: "jordan.lee@domain.com",
        isCurrentUser: false,
        shareAmount: 45.0,
        status: "paid",
        settledAt: "2026-09-02T16:20:00.000Z",
      },
    ],
  },
  {
    id: "sb-4",
    title: "Weekend Team BBQ Supplies",
    date: "2026-08-28",
    category: "Groceries & Food",
    totalAmount: 240.0,
    paidBy: "Alex Morgan",
    paidByCurrentUser: true,
    payerAccountId: "acc-3",
    splitMethod: "equal",
    notes: "Charcoal, steaks, beverages, and dessert for park cookout",
    status: "partial",
    createdAt: "2026-08-28T14:00:00.000Z",
    participants: [
      { id: "p-401", name: "Alex Morgan", email: "alex.morgan@finance.io", isCurrentUser: true, shareAmount: 60.0, status: "paid", settledAt: "2026-08-28T14:00:00.000Z" },
      { id: "p-402", name: "Sarah Jenkins", email: "sarah.j@techcorp.com", isCurrentUser: false, shareAmount: 60.0, status: "paid", settledAt: "2026-08-29T11:00:00.000Z" },
      { id: "p-403", name: "David Kim", email: "david.kim@designco.com", isCurrentUser: false, shareAmount: 60.0, status: "unpaid" },
      { id: "p-404", name: "Elena Rostova", email: "elena.r@gmail.com", isCurrentUser: false, shareAmount: 60.0, status: "unpaid" },
    ],
  },
  {
    id: "sb-5",
    title: "Concert Tickets & Parking",
    date: "2026-08-22",
    category: "Dining Out & Entertainment",
    totalAmount: 360.0,
    paidBy: "Sarah Jenkins",
    paidByCurrentUser: false,
    splitMethod: "equal",
    notes: "Indie rock concert admission and VIP parking pass",
    status: "settled",
    createdAt: "2026-08-22T19:30:00.000Z",
    participants: [
      { id: "p-501", name: "Sarah Jenkins", email: "sarah.j@techcorp.com", isCurrentUser: false, shareAmount: 120.0, status: "paid", settledAt: "2026-08-22T19:30:00.000Z" },
      { id: "p-502", name: "Alex Morgan", email: "alex.morgan@finance.io", isCurrentUser: true, shareAmount: 120.0, status: "paid", settledAt: "2026-08-23T10:15:00.000Z" },
      { id: "p-503", name: "Liam O'Connor", email: "liam.oc@gmail.com", isCurrentUser: false, shareAmount: 120.0, status: "paid", settledAt: "2026-08-23T18:00:00.000Z" },
    ],
  },
  {
    id: "sb-6",
    title: "Road Trip Gas & Highway Tolls",
    date: "2026-08-18",
    category: "Transportation & Gas",
    totalAmount: 150.0,
    paidBy: "Alex Morgan",
    paidByCurrentUser: true,
    payerAccountId: "acc-3",
    splitMethod: "equal",
    notes: "Fuel fill-ups and fastrak electronic tolls",
    status: "pending",
    createdAt: "2026-08-18T16:45:00.000Z",
    participants: [
      { id: "p-601", name: "Alex Morgan", email: "alex.morgan@finance.io", isCurrentUser: true, shareAmount: 50.0, status: "paid", settledAt: "2026-08-18T16:45:00.000Z" },
      { id: "p-602", name: "David Kim", email: "david.kim@designco.com", isCurrentUser: false, shareAmount: 50.0, status: "unpaid" },
      { id: "p-603", name: "Marcus Vance", email: "marcus.v@gmail.com", isCurrentUser: false, shareAmount: 50.0, status: "unpaid" },
    ],
  },
  {
    id: "sb-7",
    title: "Coffee & Pastries Strategy Session",
    date: "2026-08-14",
    category: "Dining Out & Entertainment",
    totalAmount: 48.0,
    paidBy: "Alex Morgan",
    paidByCurrentUser: true,
    payerAccountId: "acc-1",
    splitMethod: "equal",
    notes: "Quarterly planning brainstorm breakfast",
    status: "settled",
    createdAt: "2026-08-14T09:15:00.000Z",
    participants: [
      { id: "p-701", name: "Alex Morgan", email: "alex.morgan@finance.io", isCurrentUser: true, shareAmount: 24.0, status: "paid", settledAt: "2026-08-14T09:15:00.000Z" },
      { id: "p-702", name: "Jordan Lee", email: "jordan.lee@domain.com", isCurrentUser: false, shareAmount: 24.0, status: "paid", settledAt: "2026-08-14T14:30:00.000Z" },
    ],
  },
  {
    id: "sb-8",
    title: "Board Game Cafe Night",
    date: "2026-08-10",
    category: "Dining Out & Entertainment",
    totalAmount: 96.0,
    paidBy: "Elena Rostova",
    paidByCurrentUser: false,
    splitMethod: "equal",
    notes: "Hourly game fee plus craft sodas and snacks",
    status: "pending",
    createdAt: "2026-08-10T21:00:00.000Z",
    participants: [
      { id: "p-801", name: "Elena Rostova", email: "elena.r@gmail.com", isCurrentUser: false, shareAmount: 24.0, status: "paid", settledAt: "2026-08-10T21:00:00.000Z" },
      { id: "p-802", name: "Alex Morgan", email: "alex.morgan@finance.io", isCurrentUser: true, shareAmount: 24.0, status: "unpaid" },
      { id: "p-803", name: "Sarah Jenkins", email: "sarah.j@techcorp.com", isCurrentUser: false, shareAmount: 24.0, status: "paid", settledAt: "2026-08-11T12:00:00.000Z" },
      { id: "p-804", name: "Liam O'Connor", email: "liam.oc@gmail.com", isCurrentUser: false, shareAmount: 24.0, status: "unpaid" },
    ],
  },
  {
    id: "sb-9",
    title: "Grocery Restock & Cleaning Packs",
    date: "2026-08-05",
    category: "Groceries & Food",
    totalAmount: 185.0,
    paidBy: "Alex Morgan",
    paidByCurrentUser: true,
    payerAccountId: "acc-3",
    splitMethod: "equal",
    notes: "Bulk cleaning paper, pantry condiments, olive oils",
    status: "partial",
    createdAt: "2026-08-05T13:20:00.000Z",
    participants: [
      { id: "p-901", name: "Alex Morgan", email: "alex.morgan@finance.io", isCurrentUser: true, shareAmount: 92.5, status: "paid", settledAt: "2026-08-05T13:20:00.000Z" },
      { id: "p-902", name: "Jordan Lee", email: "jordan.lee@domain.com", isCurrentUser: false, shareAmount: 92.5, status: "unpaid" },
    ],
  },
  {
    id: "sb-10",
    title: "Escape Room Adventure",
    date: "2026-07-28",
    category: "Dining Out & Entertainment",
    totalAmount: 200.0,
    paidBy: "David Kim",
    paidByCurrentUser: false,
    splitMethod: "equal",
    notes: "Sci-fi themed escape room challenge",
    status: "settled",
    createdAt: "2026-07-28T18:00:00.000Z",
    participants: [
      { id: "p-1001", name: "David Kim", email: "david.kim@designco.com", isCurrentUser: false, shareAmount: 50.0, status: "paid", settledAt: "2026-07-28T18:00:00.000Z" },
      { id: "p-1002", name: "Alex Morgan", email: "alex.morgan@finance.io", isCurrentUser: true, shareAmount: 50.0, status: "paid", settledAt: "2026-07-29T10:00:00.000Z" },
      { id: "p-1003", name: "Sarah Jenkins", email: "sarah.j@techcorp.com", isCurrentUser: false, shareAmount: 50.0, status: "paid", settledAt: "2026-07-29T14:00:00.000Z" },
      { id: "p-1004", name: "Marcus Vance", email: "marcus.v@gmail.com", isCurrentUser: false, shareAmount: 50.0, status: "paid", settledAt: "2026-07-30T09:00:00.000Z" },
    ],
  },
  {
    id: "sb-11",
    title: "Airport Rideshare Split",
    date: "2026-07-20",
    category: "Transportation & Gas",
    totalAmount: 76.0,
    paidBy: "Alex Morgan",
    paidByCurrentUser: true,
    payerAccountId: "acc-3",
    splitMethod: "equal",
    notes: "Late night airport return ride home",
    status: "pending",
    createdAt: "2026-07-20T23:45:00.000Z",
    participants: [
      { id: "p-1101", name: "Alex Morgan", email: "alex.morgan@finance.io", isCurrentUser: true, shareAmount: 38.0, status: "paid", settledAt: "2026-07-20T23:45:00.000Z" },
      { id: "p-1102", name: "Liam O'Connor", email: "liam.oc@gmail.com", isCurrentUser: false, shareAmount: 38.0, status: "unpaid" },
    ],
  },
  {
    id: "sb-12",
    title: "Sushi Omakase Celebration",
    date: "2026-07-15",
    category: "Dining Out & Entertainment",
    totalAmount: 420.0,
    paidBy: "Alex Morgan",
    paidByCurrentUser: true,
    payerAccountId: "acc-3",
    splitMethod: "equal",
    notes: "Project launch celebration dinner with core team",
    status: "partial",
    createdAt: "2026-07-15T20:00:00.000Z",
    participants: [
      { id: "p-1201", name: "Alex Morgan", email: "alex.morgan@finance.io", isCurrentUser: true, shareAmount: 140.0, status: "paid", settledAt: "2026-07-15T20:00:00.000Z" },
      { id: "p-1202", name: "Sarah Jenkins", email: "sarah.j@techcorp.com", isCurrentUser: false, shareAmount: 140.0, status: "paid", settledAt: "2026-07-16T11:00:00.000Z" },
      { id: "p-1203", name: "David Kim", email: "david.kim@designco.com", isCurrentUser: false, shareAmount: 140.0, status: "unpaid" },
    ],
  },
];

export const INITIAL_FRIENDS: Friend[] = [
  {
    id: "fr-1",
    name: "Sarah Jenkins",
    email: "sarah.j@techcorp.com",
    status: "accepted",
    createdAt: "2026-08-01T10:00:00.000Z",
  },
  {
    id: "fr-2",
    name: "David Kim",
    email: "david.kim@designco.com",
    status: "accepted",
    createdAt: "2026-08-05T14:30:00.000Z",
  },
  {
    id: "fr-3",
    name: "Marcus Vance",
    email: "marcus.v@gmail.com",
    status: "accepted",
    createdAt: "2026-08-10T09:15:00.000Z",
  },
  {
    id: "fr-4",
    name: "Elena Rostova",
    email: "elena.r@gmail.com",
    status: "accepted",
    createdAt: "2026-08-15T16:20:00.000Z",
  },
  {
    id: "fr-5",
    name: "Chloe Zhao",
    email: "chloe.z@studio.io",
    status: "accepted",
    createdAt: "2026-08-20T11:00:00.000Z",
  },
  {
    id: "fr-6",
    name: "Ryan Cooper",
    email: "ryan.c@agency.com",
    status: "accepted",
    createdAt: "2026-08-25T13:45:00.000Z",
  },
];

